import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
import { Navbar } from "@/components/Nav";
import { ThemeProvider } from "@/context/ThemeProvider";
import { SideNav, SideNavDrawerMobile } from "@/components/SideNav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Agile Arc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Navbar />
            <SideNav />
            <SideNavDrawerMobile>
              <SideNav isMobileView={true} />
            </SideNavDrawerMobile>
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
